export const PROFILE_SETUP_TOTAL_STEPS = 6;

export const INDIAN_CITIES = [
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Hyderabad',
  'Ahmedabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Coimbatore',
  'Kochi',
  'Nashik',
  'Agra',
  'Meerut',
  'Varanasi',
  'Srinagar',
  'Chandigarh',
  'Mysuru',
  'Gurugram',
  'Noida',
  'Faridabad',
  'Rajkot',
  'Other',
].sort((a, b) => a.localeCompare(b));

export const QUALIFICATIONS = [
  '10th pass',
  '12th pass',
  'Diploma',
  'Graduate (B.A / B.Com / B.Sc)',
  'B.Tech / B.E.',
  'Postgraduate (M.A / M.Com / M.Sc)',
  'MBA',
  'MCA',
  'PhD',
  'Other',
];

export const SALARY_OPTIONS = [
  { id: 'unspecified', label: 'Prefer not to say' },
  { id: 'below15k', label: 'Below ₹15,000 / mo' },
  { id: '15kto30k', label: '₹15k – 30k / mo' },
  { id: '30kto50k', label: '₹30k – 50k / mo' },
  { id: '50kto80k', label: '₹50k – 80k / mo' },
  { id: '80kto1_2L', label: '₹80k – 1.2L / mo' },
  { id: '1_2Lplus', label: '₹1.2L & above / mo' },
] as const;

export const JOB_CATEGORIES = [
  { id: 'it', label: 'IT & Software' },
  { id: 'sales', label: 'Sales' },
  { id: 'marketing', label: 'Marketing' },
  { id: 'operations', label: 'Operations' },
  { id: 'hr', label: 'HR & Admin' },
  { id: 'finance', label: 'Finance & Accounts' },
  { id: 'healthcare', label: 'Healthcare' },
  { id: 'education', label: 'Education' },
  { id: 'logistics', label: 'Logistics' },
  { id: 'retail', label: 'Retail' },
  { id: 'hospitality', label: 'Hospitality' },
  { id: 'manufacturing', label: 'Manufacturing' },
  { id: 'other', label: 'Other' },
] as const;
